module Trycourier
  module Errors
    class Error < StandardError
      attr_accessor cause: StandardError?
    end

    class ConversionError < Trycourier::Errors::Error
      def cause: -> StandardError?

      def initialize: (
        on: Class,
        method: Symbol,
        target: top,
        value: top,
        ?cause: StandardError?
      ) -> void
    end

    class APIError < Trycourier::Errors::Error
      attr_accessor url: URI::Generic

      attr_accessor status: Integer?

      attr_accessor headers: ::Hash[String, String]?

      attr_accessor body: top?

      def initialize: (
        url: URI::Generic,
        ?status: Integer?,
        ?headers: ::Hash[String, String]?,
        ?body: Object?,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIConnectionError < Trycourier::Errors::APIError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?headers: ::Hash[String, String]?,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APITimeoutError < Trycourier::Errors::APIConnectionError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?headers: ::Hash[String, String]?,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIStatusError < Trycourier::Errors::APIError
      def self.for: (
        url: URI::Generic,
        status: Integer,
        headers: ::Hash[String, String]?,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> instance

      def initialize: (
        url: URI::Generic,
        status: Integer,
        headers: ::Hash[String, String]?,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> void
    end

    class BadRequestError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: 400
    end

    class AuthenticationError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: 401
    end

    class PermissionDeniedError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: 403
    end

    class NotFoundError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: 404
    end

    class ConflictError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: 409
    end

    class UnprocessableEntityError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: 422
    end

    class RateLimitError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: 429
    end

    class InternalServerError < Trycourier::Errors::APIStatusError
      HTTP_STATUS: Range[Integer]
    end
  end
end
